name: hrms
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 3.0.0+3
# adb connect 192.168.1.13:39923
environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  android_intent_plus: ^5.1.0
  connectivity: ^3.0.6
  crop_image: ^1.0.13
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_bloc: ^8.1.2
  flutter_carousel_widget: ^3.1.0
  flutter_event_calendar: ^1.0.0
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^17.2.3
  flutter_month_picker: ^0.0.1
  flutter_native_splash: ^2.3.7
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.10.1
  http: ^1.0.0
  image: ^4.1.3
  image_cropper: ^1.4.1
  image_picker: ^1.0.7
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.0+4
  ntp: ^2.0.0
  open_file: ^3.2.1
  path: ^1.8.0
  path_provider: ^2.0.10
  permission_handler: ^11.0.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  screenshot: ^3.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  syncfusion_flutter_calendar: ^21.2.3
  timeago: ^3.3.0
  url_launcher: ^6.3.0
  skeletonizer: ^1.4.3
  wakelock_plus: ^1.2.4
  workmanager: ^0.5.1
  crypto: ^3.0.3
  encrypt: ^5.0.1




flutter_native_splash:
  # background color for the splash screen
  color: "#ffffff"
  # path to your splash screen image
  image: assets/background_layer_2.png
  # whether to display the splash screen on Android
  android: true
  # whether to display the splash screen on iOS
  ios: true
  # gravity of the image for Android (e.g., center, top, bottom)
  android_gravity: center
  # content mode of the image for iOS (e.g., scaleToFill, scaleAspectFit, scaleAspectFill)
  ios_content_mode: scaleAspectFill
  # whether to display the splash screen in fullscreen mode
  fullscreen: true
  # optional background image for Android
  android_background_image: assets/background_layer_2.png
  # optional background image for iOS
  ios_background_image: assets/background_layer_2.png

#flutter_native_splash:
#  android: true
#  ios: true
#  web: false
#  color: "#024959"
#  image: "assets/background_layer_2.png"
#   andriod_14:
#      icon_background_color: "#f7f6f1"
#      icon_background_color_dark: "#272727"
#      image: assets/background_layer_2.png
#      image_dark: assets/background_layer_2.png
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background_layer.png
    - assets/background_layer_1.png
    - assets/background_layer_2.png
    - assets/cislogo-new.svg
    - assets/profile_icon.png
    - assets/profile_icon_1.png
    - assets/user.png
    - assets/women-emp.jpg
    - assets/user_1.png
    - assets/logo_png.png
    - assets/side_navi_bg.jpg
    - assets/2560114.svg
    - assets/atten.svg
    - assets/leave_8.svg
    - assets/app_logo.png
    - assets/hrms_logo.png
    - assets/men_emp.jpg
    - assets/right_n.svg
    - assets/caution-sign.png
    - assets/cake.png
    - assets/cakedecoration.png
    - assets/holiday.png
    - assets/ic_add.png
    - assets/header_bg_image.jpg
    - assets/bg_image1.jpg
    - assets/bg_image2.jpg
    - assets/add_a_photo.svg
    - assets/fileuploadicon.svg
    - assets/hrmsgeotrack.sqlite
    - assets/card_bg_image.jpg
    - assets/nextcircle.png
    - assets/home.svg
    - assets/Profile_new.svg
    - assets/circleuser.svg
    - assets/overview.svg
    - assets/addlead.svg
    - assets/calendar-day.svg
    - assets/refresh.svg
    - assets/backup.svg
    - assets/birthday_cake2.jpg



  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Calibri
      fonts:
        - asset: fonts/Calibri.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
